GEMINI_DEFAULT=AIzaSyD8CT-W3XyZ_L5l9C5VwvLyeShf_GSdi0w
GROQ_DEFAULT=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
OPENROUTER_DEFAULT=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
CHATGPT_DEFAULT=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
