/*
 * Copyright (C) 2026 Toolz Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.frerox.toolz.data.whisper

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

// ─────────────────────────────────────────────────────────────
// Profile
// ─────────────────────────────────────────────────────────────

@Serializable
data class WhisperProfile(
    val id: String = "",
    val username: String = "",
    @SerialName("display_name") val displayName: String? = null,
    val bio: String? = null,
    @SerialName("avatar_url") val avatarUrl: String? = null,
    @SerialName("is_private") val isPrivate: Boolean = false,
    @SerialName("public_key") val publicKey: String? = null,
    @SerialName("created_at") val createdAt: String = "",
    @SerialName("updated_at") val updatedAt: String = "",
) {
    /** Display name with username fallback */
    val effectiveName: String get() = displayName?.takeIf { it.isNotBlank() } ?: username

    /** First letter of effective name for avatar initials */
    val avatarInitial: String get() = effectiveName.firstOrNull()?.uppercase() ?: "?"
}

@Serializable
data class WhisperProfileUpdate(
    val username: String? = null,
    @SerialName("display_name") val displayName: String? = null,
    val bio: String? = null,
    @SerialName("avatar_url") val avatarUrl: String? = null,
    @SerialName("is_private") val isPrivate: Boolean? = null,
)

// ─────────────────────────────────────────────────────────────
// Messages
// ─────────────────────────────────────────────────────────────

@Serializable
data class WhisperMessage(
    val id: String = "",
    @SerialName("sender_id") val senderId: String = "",
    @SerialName("receiver_id") val receiverId: String = "",
    val content: String = "",
    @SerialName("content_iv") val contentIv: String? = null,   // For Phase 2 E2E
    @SerialName("is_read") val isRead: Boolean = false,
    @SerialName("created_at") val createdAt: String = "",
) {
    fun isSentByMe(myUserId: String) = senderId == myUserId
}

@Serializable
data class WhisperMessageInsert(
    @SerialName("sender_id") val senderId: String,
    @SerialName("receiver_id") val receiverId: String,
    val content: String,
    @SerialName("content_iv") val contentIv: String? = null,
)

/**
 * A conversation summary — the latest message thread with another user.
 */
data class WhisperConversation(
    val otherUser: WhisperProfile,
    val lastMessage: WhisperMessage,
    val unreadCount: Int,
)

// ─────────────────────────────────────────────────────────────
// Friends
// ─────────────────────────────────────────────────────────────

enum class FriendStatus { PENDING, ACCEPTED, BLOCKED, NONE }

@Serializable
data class WhisperFriendship(
    val id: String = "",
    @SerialName("user_a") val userA: String = "",
    @SerialName("user_b") val userB: String = "",
    val status: String = "pending",
    @SerialName("created_at") val createdAt: String = "",
    @SerialName("updated_at") val updatedAt: String = "",
) {
    fun friendStatus(): FriendStatus = when (status) {
        "accepted" -> FriendStatus.ACCEPTED
        "pending"  -> FriendStatus.PENDING
        "blocked"  -> FriendStatus.BLOCKED
        else       -> FriendStatus.NONE
    }

    fun otherUserId(myId: String): String = if (userA == myId) userB else userA
    fun iRequested(myId: String): Boolean = userA == myId
}

@Serializable
data class WhisperFriendshipInsert(
    @SerialName("user_a") val userA: String,
    @SerialName("user_b") val userB: String,
)

// ─────────────────────────────────────────────────────────────
// Auth Token (anonymous)
// ─────────────────────────────────────────────────────────────

/**
 * The anonymous authentication token generated by the client.
 * The raw [token] must be saved securely by the user — it acts as their password.
 * It is NEVER sent to the server in plain form.
 */
data class WhisperAnonToken(
    val token: String,          // 64-char hex string — user must save this!
    val virtualEmail: String,   // SHA-256(token) + "@anon.toolz"
    // password derived from SHA-512(token) — kept in memory only
)

// ─────────────────────────────────────────────────────────────
// UI State sealed classes
// ─────────────────────────────────────────────────────────────

sealed class WhisperAuthState {
    object Idle : WhisperAuthState()
    object Loading : WhisperAuthState()
    data class Error(val message: String) : WhisperAuthState()
    object Authenticated : WhisperAuthState()
}

data class WhisperUiState(
    val isLoading: Boolean = false,
    val currentProfile: WhisperProfile? = null,
    val conversations: List<WhisperConversation> = emptyList(),
    val friends: List<WhisperProfile> = emptyList(),
    val pendingIncoming: List<WhisperFriendship> = emptyList(),
    val pendingOutgoing: List<WhisperFriendship> = emptyList(),
    val searchResults: List<WhisperProfile> = emptyList(),
    val error: String? = null,
)

data class WhisperChatUiState(
    val isLoading: Boolean = false,
    val otherUser: WhisperProfile? = null,
    val messages: List<WhisperMessage> = emptyList(),
    val friendStatus: FriendStatus = FriendStatus.NONE,
    val iAmRequester: Boolean = false,
    val error: String? = null,
)
